ALTER TABLE council_department
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE council_department_role
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE council_member
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE council_role_permission
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
